### ISSUE TITLE
Change Weight axis range from 250-900 to 100-900

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Roboto#24]
Currently the Weight axis values in `fvar` do not go down to 100, as expected for CSS, but have carried over the legacy OS/2 table values which went down to 250 as a workaround for Windows auto-bolding of values of 249 and below. 

Today:

```xml
<Axis>
  <AxisTag>wght</AxisTag>
  <MinValue>250.0</MinValue>
  <DefaultValue>400.0</DefaultValue>
  <MaxValue>900.0</MaxValue>
</Axis>
```
What I expect:

```xml
<Axis>
  <AxisTag>wght</AxisTag>
  <MinValue>100.0</MinValue>
  <DefaultValue>400.0</DefaultValue>
  <MaxValue>900.0</MaxValue>
</Axis>
```

**Comment by davelab6** [comment]
@paleydreier please schedule this :)

**Comment by paleydreier** [comment]
cc @sannorozco @pichotta

**Comment by dberlow** [comment]
Well, fvar are you wish, but...
Having the wght min at 250’s not such a bad thing because it’s not that light. 

On Oct 15, 2018, at 8:24 PM, Dave Crossland <notifications@github.com> wrote:

Currently the Weight axis values in fvar do not go down to 100, as expected for CSS, but have carried over the legacy OS/2 table values which went down to 250 as a workaround for Windows auto-bolding of values of 249 and below.

Today:

<Axis>
  <AxisTag>wght</AxisTag>
  <MinValue>250.0</MinValue>
  <DefaultValue>400.0</DefaultValue>
  <MaxValue>900.0</MaxValue>
</Axis>
What I expect:

<Axis>
  <AxisTag>wght</AxisTag>
  <MinValue>100.0</MinValue>
  <DefaultValue>400.0</DefaultValue>
  <MaxValue>900.0</MaxValue>
</Axis>

**Comment by sannorozco** [comment]
Now both VFs have corrected fvar tables:

—Roboto-VF.ttf
—Roboto-min-VF.ttf

**Comment by davelab6** [comment]
I see in https://github.com/TypeNetwork/Roboto/commit/47598f229c77f87ecfc2e3767a6e2402e92f7c71 you did update only the Roboto-min-VF.ttf

Please check in Roboto-VF.ttf and the sources :)

**Comment by sannorozco** [comment]
Yes, only Roboto-min-VF.ttf needed to update far with these values, I checked again and far on both VFs seems good. Made a small update in min.designspace.

**Comment by davelab6** [comment]
@sannorozco @dberlow can this issue be closed?
