### ISSUE TITLE
STAT table is incorrect

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Roboto#63]
Each instance has the ElidableAxisValueName flag set and they all have linked values. 

Please see how the ElidableAxisValueName and linked values are used in this [.stylespace](https://github.com/googlefonts/Inconsolata/pull/44/files#diff-4ee49a0663a93442fdcc6a1213fd37ca)

**Comment by sannorozco** [comment]
Updated

**Comment by vitorsr** [comment]
@m4rc1e, sorry for replying to a closed issue but I did not want to open a new one.

I believe there are still inconsistencies with the STAT table, namely a named SemiBold weight instance present in fvar that overlaps with the Medium weight definition in STAT.

-   fvar

```xml
    <!-- SemiBold -->
    <!-- PostScript: Roboto-SemiBold -->
    <NamedInstance flags="0x0" postscriptNameID="302" subfamilyNameID="264">
      <coord axis="wght" value="600.0"/>
      <coord axis="wdth" value="100.0"/>
      <coord axis="ital" value="0.0"/>
    </NamedInstance>
```

-   STAT

```xml
      <AxisValue index="6" Format="2">
        <AxisIndex value="1"/>
        <Flags value="0"/>
        <ValueNameID value="263"/>  <!-- Medium -->
        <NominalValue value="500.0"/>
        <RangeMinValue value="450.0"/>
        <RangeMaxValue value="650.0"/>
      </AxisValue>
```

In the build script, the STAT is generated with [gen_stat.py](https://github.com/googlefonts/roboto-classic/blob/v3.005/scripts/gen_stat.py).

In addition, I believe it would be best if the Roman 'ital' variation had a linked value for style mapping.

I am not sure if either was intentional or not, so please forgive my not knowing.
