### ISSUE TITLE
Some glyphs do not have hints

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Roboto#70]
The following glyphs don't have VTT hints:
'.notdef', 'uni0488', 'uni0489', 'lessequal', 'greaterequal', 'uniFFFC', 'uniFFFD'

cc @mikedug

**Comment by mikedug** [comment]
hi Marc
for some glyphs, because I was mindful of file size, and because of the complex nature of the glyphs, I did not include hinting. Less equal and greaterequal should have hints, this is a bug

**.notdef =** This glyph renders ok, without hints. I can update to add hinting
**uni0488 =** COMBINING CYRILLIC HUNDRED THOUSANDS SIGN. This is a complex glyph shape, that requires a lot of hinting code. It is more difficult to make this glyph look better with hinting, than to leave it render from the outline unnhinted. The glyph renders ok without hinting. I can add hinting to this glyph if required? my recommendation is to leave it unhinted.
uni0489 = Combining Cyrillic Millions Sign. This is a complex glyph shape, that requires a lot of hinting code. It is more difficult to make this glyph look better with hinting. The glyph renders ok without hinting. I can add hinting to this glyph if required? my recommendation is to leave it unhinted.
**lessequal =** should have hinting. I can add this
**greaterequal =** should have hinting. I can add this
**uniFFFC =** This is a VERY complex glyph shape, that requires **a lot** of hinting code. It is more difficult to make this glyph look better with hinting. The glyph renders ok without hinting. I can add hinting to this glyph if required? my recommendation is to leave it unhinted.
**uniFFFD =** This is a complex glyph shape, that requires a lot of hinting code. It is more difficult to make this glyph look better with hinting. The glyph renders ok without hinting. I can add hinting to this glyph if required? my recommendation is to leave it unhinted.

please advise, and I can work with you to get you the updated hinting.

thanks
Mike

**Comment by m4rc1e** [comment]
Thanks for the info. I'm happy to keep the glyphs you mentioned unhinted.

Please hint lessequal and greaterequal in an existing ttf and open a PR containing the font. I'll then extract the hints and include them in the vtt-hinting.ttx file.

**Comment by mikedug** [comment]
I have updated the hints and opened a PR. Added hinting to uni 2264 and 2265 Please let me know if when this is successfully updated from your side

**Comment by m4rc1e** [comment]
Thanks, hints in #71 look good.
