### ISSUE TITLE
TTF file gone for a walk

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Roboto#75]
`sources/master_ttf/Roboto-Regular.ttf` should be `/fonts/Roboto[ital,wdth,wght].ttf` :)

**Comment by m4rc1e** [comment]
This was intentional, https://github.com/TypeNetwork/Roboto/pull/74#issue-436534133. I do not want anyone committing binaries themselves to this repo. I only trust the fonts which are generated by the CI.

Speaking of releases, I've finally tagged [v.3000](https://github.com/TypeNetwork/Roboto/releases/tag/v3.000). I also want us to keep fonts tagged for this project since it allows us to write release notes for each tag and will help us diagnose user issues better.

**Comment by rsheeter** [comment]
Might want to remove the reference to /fonts from the home readme since /fonts seems not to exist anymore.

**Comment by davelab6** [comment]
Fixed https://github.com/TypeNetwork/Roboto/commit/3acbbb0e841a09d2642f3b95f847cd89542af8eb
